version: "3.7"

services:
  gazebo:
    network_mode: host
    networks: null

  slam:
    network_mode: host
    networks: null

  webapp:
    network_mode: host
    networks: null
    ports: []

networks: null